name: safebox
description: "A new Flutter project."

publish_to: 'none'
version: 0.1.0

platforms:
  android:
  linux:
  windows:
  web:

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  crypto: ^3.0.3
  path_provider: ^2.1.2
  pointycastle: ^3.9.1
  multicast_dns: ^0.3.3
  network_info_plus: ^4.0.1
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true